on:
  workflow_dispatch:
  push:
permissions:
  id-token: write
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::084963261788:role/github-actions-terraform
        aws-region: eu-west-1
