on:
  workflow_dispatch:
  push:
  
permissions:
  id-token: write
  contents: write
  
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: Clone Source Code 
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::084963261788:role/github-actions-terraform
        aws-region: eu-west-1
    - name: Run Terraform Init command
      run: terraform init
    - name: Run Terraform Plan command
      run: terraform plan
    - name: Run Terraform Apply command
      run: terraform apply -auto-approve
    - name: terraform State File
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updating Terraform State File
        file_pattern: terraform.tfstate
      
